### ISSUE TITLE
bindED Error - '.', hexadecimal value 0x00, is an invalid character. Line 2, position 1.

### ISSUE THREAD

**Issue by dmon82** [Corysia/bindED#6]
I'm getting this error every time I'm calling the plugin, and I can't figure out why. There's no \0 value anywhere in EDMap.txt

**Comment by Corysia** [comment]
Did this just start happening after last nights patch?

There are three separate points where bindED could print out that error.  The first is loading EDMap.txt, the other two are when loading your keybindings.  It's possible it's your Bindings file.  I will improve the error messaging to narrow it down.

**Comment by dmon82** [comment]
I'm not sure if it happened after the patch, I've really just returned after almost exactly a 1 year hiatus from Elite and thrown Malic_VR's VA profile into my VA. I've started working on my own VA plugin and new profile, parsing the Custom.3.0.binds as well as using the data from EDMap.txt, and have not come across any 0x00 character.

In the meantime, Elite is not showing the "Custom" binds in the drop down of the controls options anymore lol... everything is just being troublesome right now ;P I wish I could be of more help, it's really not much to go on, and I'm still stuck on working with VS2013 (VS v12.00), so compiling 3rd party code of newer VS/.NET/C# versions always becomes an inconvenience.

**Comment by Corysia** [comment]
I will try to build a dev version of what is in the development branch tonight and point you to an executable you can try -- that should at least give us more info about what file is failing.  Meanwhile, can you attach your EDMap.txt and binds file here so I can look at them?

If I recall, yes, when Beyond came out, the Custom 3.0 Binds option vanished.  I use a Saitek x52 and needed to create a new binding file from that template.  I haven't yet seen a problem with my bindED reading a file.  Also, I think both ED and bindED simply go off of the last modified date of the file, reading the 'newest', whatever it's called.

Like you, I haven't a lot of access to the newer .NET stuff.  I work on Mac, so I can't even compile or run VA most of the day.  I've a narrow window in the evening where I can poke with this and/or play ED.  I could probably fake most of this with the newer .NET that's available on Mac now, but bindED has one library call that requires Windows.

**Comment by Corysia** [comment]
Attached is a build with better logging and the small changes I've done in the dev branch.  Want to give it a try?  It should tell us better which file is complaining.

[binded-setup.zip](https://github.com/Corysia/bindED/files/3144602/binded-setup.zip)

**Comment by dmon82** [comment]
I was a bit drunk last Thursday, and I've (more or less without thinking) deleted the Custom.3.0.binds file in a swift keystroke, that was in place when the error was popping occuring. I do remember that it was about twice the size of the backup binds that ED keeps. I've no idea how that happened but it seemed it was the issue, although the error message doesn't make sense if the cause was somewhere in the XML.

It didn't really hit me until I had to re-do all the keybinds, and I'm afraid I've wasted some of your time. And on top of that, I can't reproduce it anymore of course. But I try to keep it in mind if I happen to screw things up again.

**Comment by Corysia** [comment]
No, I wouldn't say you wasted my time.  It gave me the kick in the backside to actually do something.  =)  It only took a few minutes to compile and build the installer, which now I have.  I've been so distracted by DW2, I haven't done much of anything towards this or my VAP.
